server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/activiti7_learning
    username: postgres
    password: 123456
  activiti:
    history-level: full
    check-process-definitions: false
    db-history-used: true
